skip-mev/skip-go-cosmwasm-contracts

- contracts/entry-point/src/error.rs
- contracts/entry-point/src/execute.rs
- contracts/entry-point/tests/test_execute_swap_and_action.rs
- contracts/networks/osmosis/ibc-transfer/src/contract.rs
- contracts/networks/osmosis/ibc-transfer/src/error.rs
- contracts/networks/osmosis/ibc-transfer/tests/test_execute_ibc_transfer.rs
- packages/skip/src/coins.rs
- packages/skip/src/ibc.rs
- packages/skip/src/lib.rs
Closes #5 
This PR improves the contracts ability to prevent left over funds on contract due to malformed requests by the user by:
1. Erroring if ibc fees are are specified while calling the Osmosis ibc transfer adapter contract (since ibc fees are not supported on osmosis)
2. Erroring if the user swap coin would leave funds on the contract
3. Erroring if the fee swap's specified coin out is more than what is required for the ibc fees (which would leave funds on the contract)
This PR also:
1. adds test for each of these cases
2. abstracts the IbcFeeMap into a Coins struct, which will make the transition to the official cosmwasm_std Coins struct easier in the future once 1.3 is released.
> 🥅 Improve ibc fee checks to prevent leftover funds on contracts

- contracts/entry-point/src/contract.rs
- contracts/entry-point/src/error.rs
- contracts/entry-point/tests/test_instantiate.rs
Closes #10 
This PR adds a check in entry point contract instantiation that will error if a duplicate swap venue name is provided to prevent accidental overrides.
> ✨ Error if duplicate swap venue names provided at instantiation

- contracts/networks/osmosis/swap/src/error.rs
Closes #12 
This PR removes an unused overflow error.
> 🔥 Remove unused overflow error from osmosis swap adapter

- contracts/networks/neutron/ibc-transfer/src/contract.rs
- contracts/networks/neutron/ibc-transfer/src/error.rs
- contracts/networks/neutron/ibc-transfer/src/state.rs
- contracts/networks/neutron/ibc-transfer/tests/test_execute_ibc_transfer.rs
- contracts/networks/neutron/ibc-transfer/tests/test_reply.rs
- contracts/networks/neutron/ibc-transfer/tests/test_sudo.rs
- contracts/networks/osmosis/ibc-transfer/src/contract.rs
- contracts/networks/osmosis/ibc-transfer/src/error.rs
- contracts/networks/osmosis/ibc-transfer/src/state.rs
- contracts/networks/osmosis/ibc-transfer/tests/test_execute_ibc_transfer.rs
- contracts/networks/osmosis/ibc-transfer/tests/test_reply.rs
- contracts/networks/osmosis/ibc-transfer/tests/test_sudo.rs
- packages/skip/src/ibc.rs
This PR changes the ibc transfer adapter sudo handling from:
- Old: a flow of saving amounts in storage and using those stored amounts to bank send refunds
- New: a flow of querying the contract balance to send refunded funds back to the user (which equates to the refunded fee + failed ibc transfer coin [if it exists] + dust on the contract)
The tradeoff here imo is allowing the user to receive any dust that is on the contract
The thought here is that this runs into less inaccurate storage related issues since we will only ever bank send what we actually have, but is relying on implicit accounting rather than explicit accounting.
This is related to Oak Security Audit Finding #1
Opening this up to serve as a discussion around security.
> ✨ Refund contract balance in ibc adapters instead of stored vars

- contracts/entry-point/src/execute.rs
- contracts/entry-point/tests/test_execute_post_swap_action.rs
- contracts/entry-point/tests/test_execute_swap_and_action.rs
- contracts/networks/osmosis/ibc-transfer/src/contract.rs
- packages/skip/src/entry_point.rs
This PR renames PostSwapAction enum to Action since the var name is `post_swap_action` and captures when the Action type is used. Also allows future places in the contract to use the Action enum.
> ♻️ Rename PostSwapAction enum to Action

- contracts/entry-point/tests/test_execute_swap_and_action.rs
- packages/skip/src/entry_point.rs
- packages/skip/src/swap.rs
This PR adds an optional refund address to `SwapExactCoinOut`, which will be later used when supporting the `user_swap` being a `SwapExactCoinOut` and wanting to bank send leftover assets to the user.
> ✨ Add optional refund address to SwapExactCoinOut

- contracts/entry-point/tests/test_execute_swap_and_action.rs
This PR fixes a small typo bug for the test function name.
> 🐛 fix test_execute_swap_and_action naming

- contracts/entry-point/src/error.rs
- contracts/entry-point/src/execute.rs
- contracts/entry-point/tests/test_execute_swap_and_action.rs
- packages/skip/src/swap.rs
- When the contract was originally developed, it did not have enforcement that a user would not be allowed to leave funds on contract by accident if they input a `coin_in` in `user_swap` that was less than the `remaining_coin_received` on contract.
- This was changed to be enforced after the audit findings.
- After implementing the audit changes, the logic enforced that the `coin_in` in `user_swap` was the exact same as the `remaining_coin_received`, otherwise it errors. So it no longer makes sense to accept a `coin_in` parameter if all it does is open up a vector for a user error that errors the transaction. 
1. Removes the `coin_in` field in the `SwapExactCoinIn` type
2. Removes logic in the entry point contract that used the `coin_in` field, instead just using `remaining_coin_received` …
> ⚡️ Derive user swap coin in from remaining coin received only

- contracts/entry-point/src/error.rs
- contracts/entry-point/src/execute.rs
- contracts/entry-point/tests/test_execute_post_swap_action.rs
- contracts/entry-point/tests/test_execute_swap_and_action.rs
- contracts/networks/neutron/ibc-transfer/src/contract.rs
- contracts/networks/neutron/ibc-transfer/src/error.rs
- contracts/networks/neutron/ibc-transfer/tests/test_execute_ibc_transfer.rs
- contracts/networks/osmosis/ibc-transfer/src/contract.rs
- contracts/networks/osmosis/ibc-transfer/tests/test_execute_ibc_transfer.rs
- packages/skip/src/ibc.rs
This PR:
1. changes `IbcInfo.Fee` to be of type `Option<IbcFee>` instead of a required field, since it is not required for all chains (Osmosis being an example of a chain that doesn't use ibc fees).
2. Updates the adapter and entry point contracts accordingly to handle the Some or None cases
3. Updates the tests accordingly, adding extra tests to check the logical paths from handling the Some or None cases
This makes it more explicit and doesn't have us checking each vector to see if ibc_fees is present or not.
> ⚡️ Change IBC Fee to be Optional

- contracts/entry-point/src/error.rs
- contracts/entry-point/src/execute.rs
- contracts/entry-point/tests/test_execute_swap_and_action.rs
- packages/skip/src/error.rs
- packages/skip/src/ibc.rs
- packages/skip/src/swap.rs
- Previously, the contract accepted a `coin_out` param in `SwapExactCoinOut`, but the logic would essentially ensure this `coin_out` provided matched the actual fees given in `ibc_info.fee`.
- So, since we made this enforcement, a simplification and safer flow from a caller would be such that the fee swap `coin_out` is directly derived from the provided ibc fees itself, leaving no way for the caller to specify an incorrect `coin_out`.
- Removes the `coin_out` field from `SwapExactCoinOut`
- Implements a `one_coin` method on IbcFee to ensure that if it provided it is exactly one coin (since the rest of the contract can't handle multiple ibc fee swaps anyways, and since it's an Option it should be set to None if no ibc fees are required)
- Changes the entry point contract to derive the fee …
> ⚡️ Derive Fee Swap Coin Out From IBC Fees Provided

- contracts/entry-point/src/execute.rs
- contracts/entry-point/tests/test_execute_swap_and_action.rs
- packages/skip/src/entry_point.rs
- packages/skip/src/swap.rs
This PR:
1. Creates a `Swap` enum that has two variants `SwapExactCoinIn` and `SwapExactCoinOut`
2. Changes `user_swap` from type `SwapExactCoinIn` to `Swap` enum while only supporting the `SwapExactCoinIn` variant
3. Updates test
A future PR will implement the actual `SwapExactCoinOut` logic
> ✨ Change user_swap to a Swap enum

- contracts/entry-point/src/contract.rs
- contracts/entry-point/src/error.rs
- contracts/entry-point/src/execute.rs
- contracts/entry-point/tests/test_execute_post_swap_action.rs
- contracts/entry-point/tests/test_execute_swap_and_action.rs
- packages/skip/src/entry_point.rs
This PR:
- Changes affiliate fee amount to be derived from the BPS applied to the min_coin (rather than the contract balance post-swap), allowing us to have a standardized affiliate fee calc for both SwapExactCoinIn and SwapExactCoinOut
- Moves the affiliate fee logic into swap_and_action
- Adds affiliate fee tests to swap_and_action tests
- Removes affiliate fee tests from posts_swap_action tests
> ✨ Change Affiliate Fee Logic To Be Based On Min Coin Within swap_and_action

- contracts/entry-point/src/error.rs
- contracts/entry-point/src/execute.rs
- contracts/entry-point/tests/test_execute_swap_and_action.rs
- contracts/entry-point/tests/test_user_swap.rs
This PR:
- Implements the logic for when a `user_swap`'s `swap` enum is of the variant `SwapExactCoinOut`. 
- When this happens, the entry point logic queries the swap adapter to get the `coin_in` required to obtain the specified `coin_out` (which is the `min_coin` specified by the user plus the amounts required for the affiliate fees). 
- Then it creates a refund bank send to send back to the `refund_address` provided if the refund amount > 0. 
- Then it dispatches the user swap
- Then it dispatches any affiliate fee bank sends (after the user swap so that the contract has enough balance)
- Adds tests for both success and error cases
Future PR:
- A future PR will aim to reduce copied code across fee swap and user swap logic, this PR implements the core logic in a flat manner without …
> ✨ Implement Swap Exact Coin Out Logic For User Swap

- Cargo.lock
- Cargo.toml
- Makefile
This PR upgrades:
- rustc to 1.71.0
- workspace to 0.2.0
- cosmwasm optimizer to 0.14.0
> ⬆️ Upgrade Rustc, Workspace, and Optimizer Version

- contracts/entry-point/src/contract.rs
- contracts/entry-point/src/execute.rs
- contracts/entry-point/tests/test_execute_post_swap_action.rs
- contracts/entry-point/tests/test_execute_swap_and_action.rs
- packages/skip/src/entry_point.rs
- The post swap action logic relies on querying the contract balance and then doing things with it. Under circumstances where there is no dust on contract, the swap exact out logic worked as expected because the swap only obtains the exact correct amount which is then used.
- However, if there is any dust left on the entry point contract in the desired out denom, then the post swap action logic would also send those funds, making the actual transferred coin (whether it was a bank send, contract call, or ibc transfer) to be the min_coin + leftover dust.
- This is a bug
- Passes an `exact_out` boolean to the `PostSwapAction` call based on what the user swap is.
- When the boolean is true, forces the min_coin to be the coin used in bank sends, contract calls, and ibc transfers
- Updates …
> 🐛 Enforce Coin Sent is Exact In Post Swap Actions if User Swap Is Swap Exact Out

- CHANGELOG.md
- contracts/networks/neutron/ibc-transfer/src/contract.rs
- contracts/networks/osmosis/ibc-transfer/src/contract.rs
- packages/skip/src/ibc.rs
- Previously, IBC transfer adapter contracts stored a struct that was network-specific given an ack id. This was changed in #19 to instead just store an address as a String (verified as a a valid address in entry point) on both contracts.
- This allows us to then use the same query enum for both networks
- Consolidates the multiple query enums into one.
> 🔥 Consolidate Neutron and Osmosis Query enum

- .github/workflows/pr.yml
- CHANGELOG.md
- Makefile
- contracts/entry-point/README.md
- contracts/entry-point/src/contract.rs
- contracts/entry-point/src/error.rs
- contracts/entry-point/src/execute.rs
- contracts/entry-point/tests/test_execute_post_swap_action.rs
- contracts/entry-point/tests/test_execute_swap_and_action.rs
- packages/skip/src/entry_point.rs
- schema/raw/execute.json
- schema/skip-api-entry-point.json
- Previously, the contract would throw an error if a fee_swap was provided but the post swap action was not an ibc transfer/
- This is unnecessary as the fee_swap option could instead be placed into the ibc transfer variant of the post swap action enum, enforcing this requirement via the types themselves.
- Refactors fee_swap by moving it into the Action enum's IbcTransfer variant
- Updates tests accordingly
- Changes entry point logic slightly to use an if let pattern instead of matching on the post swap action enum (since we only match on 1 variant now)
> ♻️ Refactor Fee Swap Into Ibc Transfer Variant of Action Enum

- deployed-contracts/neutron/mainnet.toml
- deployed-contracts/neutron/testnet.toml
- deployed-contracts/osmosis/mainnet.toml
- deployed-contracts/osmosis/testnet.toml
- scripts/configs/neutron.toml
- scripts/configs/osmosis.toml
- Deploys testnet and mainnet contracts to Osmosis and Neutron for the new always recover logic.
There is now a new entry point message, which has all the same params as the SwapAndAction but with an additional `recovery_addr` field, which is where info.funds() will be sent to if any error that we can catch occurs in the SwapAndAction call (out of gas is an example error we cannot catch):
```
SwapAndActionWithRecover {
user_swap: Swap,
min_coin: Coin,
timeout_timestamp: u64,
post_swap_action: Action,
affiliates: Vec<Affiliate>,
recovery_addr: Addr,
}
```
- Note: `SwapAndAction` entry point still exists for when we want to still fail a tx upon error.
> Deploy Contracts for Recover Entrypoint

- contracts/adapters/swap/astroport/src/contract.rs
- contracts/adapters/swap/astroport/src/error.rs
- contracts/adapters/swap/astroport/tests/test_execute_swap.rs
- deployed-contracts/terra/mainnet.toml
- deployed-contracts/terra/testnet.toml
- It was observed there was a bug in which our Astroport simulation queries can return results that are not able to be executed at the swap stage due to having a max_spread limit at swap which isn't taken into account on Astroport's queries.
- Relatedly, on the swap side we do not set a max_spread when we call the Astroport router contract, which defaults to a slippage limit of .005. This was decided to be changed to the max (.50) allowed on Astroport to reduce the amount of errors received from the Astroport contracts since our entry point handles the slippage we care about.
Swap Side
1. Adds a max_spread amount of .50 (50%) to the Astroport router swaps, which is the max limit that can be set (Previously without setting this param, the max_spread defaulted to Astroport's default of …
> 🐛 Astroport Slippage Fix

- contracts/adapters/swap/astroport/src/contract.rs
- contracts/adapters/swap/lido-satellite/src/contract.rs
- contracts/adapters/swap/osmosis-poolmanager/src/contract.rs
- contracts/adapters/swap/osmosis-poolmanager/src/error.rs
- deployed-contracts/neutron/mainnet.toml
- deployed-contracts/neutron/testnet.toml
- deployed-contracts/osmosis/mainnet.toml
- deployed-contracts/osmosis/testnet.toml
- deployed-contracts/terra/mainnet.toml
- deployed-contracts/terra/testnet.toml
- packages/skip/src/swap.rs
- scripts/configs/neutron.toml
- scripts/configs/osmosis.toml
- scripts/configs/terra.toml
- We want to be able to return price impact back to api callers.
- Creates two new query endpoints for swap venue adapter contracts that return a spot price in addition to the respective asset in/out depending on the simulation request. This is implemented as separate endpoints to not increase gas costs to core contract functionality.
- Updates deployed contracts to be of the latest deployment of swap venue contracts that expose the endpoints.
> Add Spot Price In Swap Simulation Query Responses

- README.md
- contracts/entry-point/src/execute.rs
- contracts/entry-point/tests/test_execute_receive.rs
- contracts/entry-point/tests/test_execute_swap_and_action.rs
- contracts/entry-point/tests/test_execute_swap_and_action_with_recover.rs
- deployed-contracts/neutron/mainnet.toml
- deployed-contracts/neutron/testnet.toml
- deployed-contracts/osmosis/mainnet.toml
- deployed-contracts/osmosis/testnet.toml
- deployed-contracts/terra/mainnet.toml
- deployed-contracts/terra/testnet.toml
- packages/skip/src/entry_point.rs
- schema/raw/execute.json
- schema/skip-api-entry-point.json
This PR makes sent_asset param optional. If sent_asset is given, we validate it. If not given, defaulting to enforcing one coin is sent via info.Funds (recover endpoint will still refund if multiple coins given).
> [API-2262] Make Sent Asset Param Optional

- Cargo.lock
- Cargo.toml
- contracts/adapters/ibc/ibc-hooks/src/contract.rs
- contracts/adapters/swap/astroport/src/contract.rs
- contracts/placeholder/Cargo.toml
- contracts/placeholder/README.md
- contracts/placeholder/src/contract.rs
- contracts/placeholder/src/lib.rs
- deployed-contracts/sei/mainnet.toml
- packages/skip/src/ibc.rs
- packages/skip/src/swap.rs
- scripts/configs/sei.toml
- scripts/deploy.py
- Deploys our contracts on Sei.
- Because Sei does not support determinsitic contract addresses (and our contracts depend on having the adapters know the entry point contract address and the entry point address knowing the adapter contract addresses to limit their calling to one another), I did a different method of deployment (changed the configs/deployments so that this can be done on any network without Instantiate2 via config):
1. Created a placeholder contract w/ only an instantiate function to be valid
2. For each adapter contract, store and instantiate a placeholder contract for it, obtaining an address
3. Deploy the entry point contract with the placeholder contract addresses for their respective adapter contract
4. Migrate the placeholder contracts to the real adapter contracts, …
> 🚀 [API-2506] Deploy on Sei

- contracts/adapters/swap/astroport/src/contract.rs
- contracts/adapters/swap/astroport/tests/test_execute_astroport_pool_swap.rs
- contracts/adapters/swap/astroport/tests/test_execute_receive.rs
- contracts/adapters/swap/astroport/tests/test_execute_swap.rs
- contracts/adapters/swap/dexter/src/contract.rs
- contracts/adapters/swap/dexter/tests/integration_test.rs
- contracts/adapters/swap/dexter/tests/test_execute_swap.rs
- contracts/adapters/swap/lido-satellite/src/contract.rs
- contracts/adapters/swap/lido-satellite/tests/test_execute_swap.rs
- contracts/adapters/swap/osmosis-poolmanager/src/contract.rs
- contracts/adapters/swap/osmosis-poolmanager/tests/test_execute_swap.rs
- contracts/adapters/swap/white-whale/src/contract.rs
- contracts/adapters/swap/white-whale/tests/test_execute_receive.rs
- contracts/adapters/swap/white-whale/tests/test_execute_swap.rs
- contracts/adapters/swap/white-whale/tests/test_execute_white_whale_pool_swap.rs
- contracts/entry-point/src/execute.rs
- contracts/entry-point/tests/test_execute_receive.rs
- contracts/entry-point/tests/test_execute_swap_and_action.rs
- contracts/entry-point/tests/test_execute_swap_and_action_with_recover.rs
- contracts/entry-point/tests/test_user_swap.rs
- packages/skip/src/error.rs
- packages/skip/src/swap.rs
- schema/raw/execute.json
- schema/skip-api-entry-point.json
This PR updates Skip API contracts to support route splitting by adding a `Route` type:
```
pub struct Route {
pub offer_asset: Asset,
pub operations: Vec<SwapOperation>,
}
```
And replacing (most) occurrences of `operations: Vec<SwapOperation>` with `routes: Vec<Route>`
This only implements the type change and updates the contract and tests to satisfy the new types, some additional work needs to be done to actually support route splitting (for example balances are used throughout the codebase to determine swap amounts, this will no longer work with multiple routes).
- packages/skip/src/swap.rs
- contracts/entry-point/src/execute.rs
> Update contract types to support route splitting

- contracts/entry-point/src/execute.rs
- contracts/entry-point/tests/test_execute_swap_and_action.rs
- contracts/entry-point/tests/test_user_swap.rs
- packages/skip/src/error.rs
- packages/skip/src/swap.rs
Updates the Entry Point contract to support multiple routes when calling `SwapExactAssetIn`.
`SwapExactAssetOut` will continue to be unsupported for the time being due to added complexity and no current integrators supporting this anyways.
> Support split routes in entry point contract

- contracts/adapters/swap/astroport/src/contract.rs
- contracts/adapters/swap/astroport/src/state.rs
- contracts/adapters/swap/astroport/tests/test_execute_astroport_pool_swap.rs
- contracts/adapters/swap/astroport/tests/test_execute_receive.rs
- contracts/adapters/swap/astroport/tests/test_execute_swap.rs
- packages/skip/src/swap.rs
Updates the Astroport adapter contract to support multiple routes.
The main change is to add an optional `offer_asset` to `AstroportPoolSwap` to allow manually setting the swap amount of an operation. With this we can set the `offer_asset` of a swap operation to the `offer_asset` of the route if it is the first operation in the route.
Most validation we will have to do regarding multiple routes appears to be done in the entry point contract, but correct me if I'm wrong.
> Support multiple routes in astroport adapter

- Cargo.lock
- Cargo.toml
- contracts/adapters/swap/dexter/src/contract.rs
- contracts/adapters/swap/dexter/tests/test_execute_swap.rs
- contracts/adapters/swap/osmosis-poolmanager/src/contract.rs
- contracts/adapters/swap/osmosis-poolmanager/tests/test_execute_swap.rs
- contracts/adapters/swap/white-whale/src/contract.rs
- contracts/adapters/swap/white-whale/src/state.rs
- contracts/adapters/swap/white-whale/tests/test_execute_receive.rs
- contracts/adapters/swap/white-whale/tests/test_execute_swap.rs
- contracts/adapters/swap/white-whale/tests/test_execute_white_whale_pool_swap.rs
- packages/skip/src/swap.rs
Updates adapter contracts to support multiple routes. Excluding:
- Astroport added in #99 
- Lido Satellite, doesn't seem relevant
Updates `osmosis-std` to access split route types
**Note:** I checked the Dexter router code and they properly track balances between swaps so the edge case found in #99 won't be an issue.
> Add split route support in all adapters

- contracts/entry-point/src/execute.rs
Emits the amount received from swaps
closes #95
> emit amount out of swap

- Cargo.lock
Updates cosmwasm-std to 1.5.4 which includes patch for the security vulnerability detailed here https://twitter.com/cosmwasm/status/1782439624608030771?s=46
> [API-2721] Update cosmwasm-std to 1.5.4

- contracts/entry-point/src/execute.rs
Adds code in the `execute_user_swap` handler that emits the swap denoms in the event attributes.
> [API-2920] emit swap denoms in event attributes

- scripts/configs/archway.toml
- scripts/configs/chihuahua.toml
- scripts/configs/injective.toml
- scripts/configs/migaloo.toml
- scripts/configs/neutron.toml
- scripts/configs/oraichain.toml
- scripts/configs/osmosis.toml
- scripts/configs/persistence.toml
- scripts/configs/sei.toml
- scripts/configs/terra.toml
- scripts/deploy.py
- scripts/deploy_injective.py
On a chain without Instantiate2 we still need to set one temporarily, this is now cleared after the contract is instantiated correctly
> do not set a contract admin

- contracts/adapters/swap/drop/src/contract.rs
- contracts/adapters/swap/drop/tests/test_queries.rs
For `SimulateSwapExactAssetIn` simulations, do not allow for simulations where the `AssetIn` is the `bonded_denom`. For `SimulateSwapExactAssetOut` simulations, do not allow for simulations where the `AssetOut` is the `remote_denom`.
> [API-2954] Drop - Do not simulate getting out of bonded denom

- contracts/entry-point/src/contract.rs
- contracts/entry-point/src/error.rs
- contracts/entry-point/src/execute.rs
- contracts/entry-point/tests/test_execute_action.rs
- packages/skip/src/entry_point.rs
- schema/raw/execute.json
- schema/skip-go-entry-point.json
- Adds 2 entry point methods, `execute_action` and `execute_action_with_recover` that allow the entry point contract to route an action without a swap
- The use case is primarily for Skip Go Fast, which will call a the entrypoint contract to handle IBC transfers / arbitrary actions for intent fulfillment with recovery logic
> Add Action Support

- Cargo.lock
- Cargo.toml
- contracts/adapters/hyperlane/Cargo.toml
- contracts/adapters/hyperlane/src/bin/hyperlane-schema.rs
- contracts/adapters/hyperlane/src/contract.rs
- contracts/adapters/hyperlane/src/error.rs
- contracts/adapters/hyperlane/src/lib.rs
- contracts/adapters/hyperlane/src/state.rs
- contracts/entry-point/src/contract.rs
- contracts/entry-point/src/error.rs
- contracts/entry-point/src/execute.rs
- contracts/entry-point/src/state.rs
- contracts/entry-point/tests/test_execute_action.rs
- contracts/entry-point/tests/test_instantiate.rs
- packages/skip/src/entry_point.rs
- packages/skip/src/hyperlane.rs
- packages/skip/src/lib.rs
- schema/raw/execute.json
- schema/raw/instantiate.json
- schema/skip-go-entry-point.json
- Implements a hyperlane remote transfer adapter contract, which takes in the coin sent to the contract along with the rest of the remote transfer metadata and calls the hyperlane warp route contract with it
- Adds the hyperlane transfer action in the entry point contract, allowing an action or post swap action to be a hyperlane transfer
- This is generally useful to allow 1-click hyperlane flows before we know the amount out of a swap
> Add Hyperlane Transfer Action Support
